apply plugin: 'com.android.library'

android {
    compileSdkVersion 31
    namespace 'com.espressif.iot.esptouch'
    defaultConfig {
        minSdkVersion 14
        targetSdkVersion 31
        versionCode 6
        versionName "v0.3.7.0"

        testInstrumentationRunner "androidx.test.runner.AndroidJUnitRunner"

    }

    buildTypes {
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android.txt'), 'proguard-rules.pro'
        }
    }

}

dependencies {
    implementation fileTree(dir: 'libs', include: ['*.jar'])
}
